In [3]:
import numpy as np

In [3]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
x[0]

0

**2차원 행렬 인덱싱**

In [5]:
x=np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
x[0]

array([0, 1, 2, 3, 4])

In [8]:
x[1,3]   #[1][3]이 아니라 [1,3]

8

**3차원 행렬 indexing**

In [5]:
x=np.arange(36).reshape(3,4,3)   #4행 3열의 행렬이 3개 있다.
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [6]:
 x[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
x[1,2]

array([18, 19, 20])

**슬라이싱**
~~~
리스트, 문자열slicing과 동일한 개념으로 사용
,를 사용하여 각 차원 별로 슬라이싱 기능
~~~

1차원 벡터 슬라이싱

In [10]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

2차원 행렬 슬라이싱

In [12]:
x=np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
x[:,1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [15]:
x[0,:2]   #슬라이싱 아닌 indexing을 사용하면 차원이 하나 감소

array([0, 1])

3차원 텐세 슬라이싱

In [18]:
x=np.arange(54).reshape(2,9,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [21]:
x[:1,0:2,:]  #마지막에 :을 안 쓰거나 slicing이 아닌 indexing 사용시 차원 유지 불기

array([[[0, 1, 2],
        [3, 4, 5]]])