# Boolean indexing으로 조건에 맞는 데이터 선택하기

~~~
ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링
브로드캐스팅을 활용하요 ndarray로 부터 bool list 얻기
~~~
> 짝수인 경우만 찾아보기

In [1]:
import numpy as np

In [3]:
x=np.random.randint(1,100,size=10)
print(x)

[65 25 30 56 15 47 62 79 82 55]


In [5]:
x%2==0

array([False, False,  True,  True, False, False,  True, False,  True,
       False])

**bool list를 index로 전달**

In [8]:
even_mask=x%2==0
print(even_mask)

[False False  True  True False False  True False  True False]


In [10]:
x[even_mask]   #True인 경우에만 값이 온다

array([30, 56, 62, 82])

In [12]:
x[x%2==0]     #위의 두 줄을 한 줄으로 줄일 수 있다

array([30, 56, 62, 82])

In [13]:
x>30   #30보다 큰 수를 boolen 형태로 나타내기

array([ True, False, False,  True, False,  True,  True,  True,  True,
        True])

In [14]:
x[x>30]

array([65, 56, 47, 62, 79, 82, 55])

# 다중조건 사용하기
~~~
파이썬 논리 연산자인 and, or, not 키워드 사용 불가
~~~
~~~
&-AND
~~~
~~~
|-OR
~~~


In [21]:
y=np.arange(5,20).reshape(3,5)

In [23]:
y%2==0
y<15

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [24]:
y[(y%2==0)&(y<15)]   #조건 2개를 and로 이을 수 있다

array([ 6,  8, 10, 12, 14])

In [25]:
y<15
y>10

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [27]:
x[(x<15)|(x>10)]

array([65, 25, 30, 56, 15, 47, 62, 79, 82, 55])

**예제) 2019년 7월 서울 평균기온 데이터**
~~~
평균기온이 25도를 넘는 날수는?
평균기온이 25도를 엄는 날의 평균 기온은?
~~~

In [30]:
temp=np.array(
    [19.1, 17.9, 22.0, 21.9, 23.0, 24.6, 22.7, 
     25.0, 26.7, 25.8, 26.1, 24.7, 26.9, 24.0, 
     23.0, 24.4, 24.3, 23.4, 24.7, 24.9, 26.1, 
     28.6, 27.3, 22.3, 21.6, 21.8, 24.1, 25.2, 
     23.8, 20.1])

In [31]:
len(temp)

30

In [32]:
temp>25.0

array([False, False, False, False, False, False, False, False,  True,
        True,  True, False,  True, False, False, False, False, False,
       False, False,  True,  True,  True, False, False, False, False,
        True, False, False])

In [33]:
temp[temp>25.0]

array([26.7, 25.8, 26.1, 26.9, 26.1, 28.6, 27.3, 25.2])

In [34]:
len(temp[temp>25.0])

8

In [35]:
np.mean(temp[temp>25.0])

26.5875