In [2]:
import numpy as np

In [3]:
np.random.rand(2,3)

array([[0.51885205, 0.06454035, 0.35153297],
       [0.72094619, 0.8416218 , 0.01467865]])

In [4]:
np.random.rand(3)

array([0.35076731, 0.03860701, 0.45182859])

In [5]:
np.random.rand(4,5,3) 

array([[[0.37107829, 0.87999541, 0.46531424],
        [0.52584686, 0.69808115, 0.41058621],
        [0.05403121, 0.79072184, 0.66177525],
        [0.85817387, 0.87352256, 0.84078548],
        [0.51580624, 0.80947097, 0.43454995]],

       [[0.89226331, 0.1200713 , 0.22978893],
        [0.92244321, 0.49668239, 0.64679156],
        [0.35880311, 0.67679698, 0.90632641],
        [0.84073564, 0.29654105, 0.99982849],
        [0.59072289, 0.05263308, 0.85272269]],

       [[0.23613806, 0.86084847, 0.16113812],
        [0.57553539, 0.4653487 , 0.43728633],
        [0.24226963, 0.18150768, 0.07917917],
        [0.89622162, 0.21967293, 0.78419369],
        [0.18155012, 0.16996665, 0.92328175]],

       [[0.99482815, 0.72197748, 0.24455451],
        [0.04280477, 0.11788304, 0.45971654],
        [0.12297299, 0.44815288, 0.54702176],
        [0.54612466, 0.64268923, 0.49607761],
        [0.8982411 , 0.15815593, 0.4116176 ]]])

In [6]:
np.random.randn(3,4)

array([[ 1.44485352, -0.73090929, -1.14353818, -0.40523801],
       [-2.5035741 , -0.1172402 ,  0.53383347,  0.43489856],
       [-0.19838059, -0.25120695, -0.1487158 ,  0.34204673]])

# 정수에서 sampling

In [7]:
np.random.randint(1,100,size=(3,5))

array([[68, 53, 63, 65, 12],
       [ 5, 89, 39, 88, 40],
       [56, 41, 49, 49, 42]])

In [8]:
np.random.randint(1,100,size=(3,))

array([76, 55, 59])

# seed 함수
>랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [9]:
np.random.seed(150)

In [10]:
np.random.randn(3,4)  #seed 함수 다음에 이것을 호출하면 이 값이 고정

array([[-0.23138325,  0.39061323,  0.35829747,  0.56624448],
       [ 0.16623399,  1.91341213,  0.30290274, -0.83082631],
       [-0.06014233, -0.09429414, -1.36774478, -0.59251809]])

# choice
~~~
주어진 1차원 ndarray로 부터 랜덤으로 샘플링
정수가 주어진 경우 np.array(해당 숫자)로 간주
~~~

In [11]:
np.random.choice(100,size=(3,4))  #0~99의 수를 3행 4열

array([[ 7, 43, 38, 62],
       [23, 45, 93, 74],
       [64, 19, 23, 67]])

In [16]:
x=np.array([1,2,3,1.5,2.6,4.9])
np.random.choice(x,size=[2,2])  #주어진 x 중에서 2,2 갖고 옴

array([[4.9, 1. ],
       [2.6, 4.9]])

In [17]:
x=np.array([1,2,3,1.5,2.6,4.9])
np.random.choice(x,size=(2,2))

array([[2., 3.],
       [2., 1.]])

**확률 분포에 따른 ndarray 생성**
~~~
uniform
normal
...
~~~

In [16]:
np.random.uniform(1.0,3.0,size=(4,5))   #uniform한 분포에서 random으로 sampling

array([[1.47538842, 1.08972456, 2.01086286, 1.75250491, 2.1856108 ],
       [2.25988375, 1.28520063, 2.8676826 , 2.89275976, 2.20459332],
       [1.77553256, 1.72637601, 1.40869055, 1.55353012, 1.49307176],
       [1.347216  , 2.93321939, 2.9140252 , 2.19594737, 2.46260151]])

In [17]:
np.random.normal(size=(3,4))
np.random.randn(3,4)  #위의 내용과 동일한 것

array([[-0.63913007, -0.33368753, -0.43760186, -1.90579488],
       [-1.22901933,  0.79489886, -1.16050814,  0.54605552],
       [ 1.16325833,  0.65887702,  0.52368926,  1.32715607]])

**unique 함수**
~~~
중복된 값을 제거하고 중복되지 않은 값의 list 출력
~~~

In [18]:
np.unique([11,11,2,2,34,31])

array([ 2, 11, 31, 34])

In [21]:
a=np.array(['a','b','b','c','a'])
index, count=np.unique(a,return_counts=True)

In [22]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [23]:
count

array([2, 2, 1], dtype=int64)