# axis(축) 이해 및 axis를 파라미터로 갖는 함수 활용하기

**axis 이해하기**
~~~
몇몇 함수에는 axis keyword 파라미터가 존재
axis값이 없는 경우에는 전체 데이터에 대해 적용
axis값이 있는 경우에는, 해당 axis를 따라서 연산 적용
axis를 파라미터로 갖는 함수를 이용하기 
~~~

>거의 대부분의 연산 함수들이 axis 파라미터 이용


>이경우 해당 값이 주어졌을 때, 해당 axis를 따라서 연산 적용,
>따라서 결과는 해당 axis가 제외된 나머지 차원의 data만 남게됨

In [4]:
import numpy as np

In [5]:
x=np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
np.sum(x, axis=0)   #1차원은 axis가 1개이고 0값을 주어야 함

105

**행렬어 적용하기**

In [12]:
y=x.reshape(3,5)   #axis은 행이 증가하는 방향이 0(위에서 아래로)이고 열이 증가하는 방향이 1(오름쪽에서 왼쪽으로)이다
print(y)

np.sum(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


105

In [13]:
np.sum(y, axis=0)

array([15, 18, 21, 24, 27])

In [15]:
np.sum(y,axis=1)

array([10, 35, 60])

In [16]:
z=np.arange(36).reshape(3,4,3)
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [17]:
np.sum(z)

630

In [19]:
np.sum(z,axis=0)   #0번째의 3이 없어지기 때문에 (4,3), 4행 3열만 남음

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [20]:
np.sum(z,axis=1)

array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

In [21]:
np.sum(z,axis=2)

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

In [23]:
np.sum(z,axis=-1)   #파이썬 index와 같이 -1은 맨 마지막 값인 2, -2는 1을 의미

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

**axis의 값이 튜플일 경우**
~~~
해당 튜플에 명시된 모든 axis에 대해서 연산
~~~

In [26]:
np.sum(z,axis=(0,1))    #0과 1번 축을 동시에 합치기

array([198, 210, 222])