# linalg 서브 모듈을 사용하여 선형대수 연산하기

In [1]:
import numpy as np

**np.linalg.inv**
~~~
역행렬을 구할 때 사용
모든 차원의 값이 같아야 함
~~~

In [4]:
x=np.random.rand(3,3)   #(3,3,3)은 가능하지만 (3,4)는 불가능 >>차원들끼리 값이 동일해야 한다
print(x)

x@np.linalg.inv(x)   #행렬끼리의 곱은 @를 사용한다
                     #np.matmul(x,np.linalg.inv(x))도 동일한 결과가 나타남

[[0.88835941 0.36323275 0.1957852 ]
 [0.31301716 0.17256617 0.57186221]
 [0.47828632 0.70097698 0.18016112]]


array([[ 1.00000000e+00, -1.04060371e-17, -4.02158713e-17],
       [-4.99927805e-17,  1.00000000e+00,  5.61182485e-18],
       [-6.04010942e-17, -2.40158890e-17,  1.00000000e+00]])

**np.linalg.solve**
~~~
Ax=B 형태의 선형대수식 솔루션을 제공
예제) 호랑이와 홍합의 합: 25 호랑이 다리와 홍합 다리의 합은 64
     x+y=25
     2x+4y=64
~~~
>선형대수 문제를 풀어주는 함수

In [5]:
A=np.array([[1,1],[2,4]])
B=np.array([25,64])

x=np.linalg.solve(A,B)
print(x)

np.allclose(A@x, B)

[18.  7.]


True