In [1]:
import numpy as np

**브로드캐스팅**

~~~
shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행,
연산되는 두 ndarray가 다른 shape을 갖는 경우 브로드캐스팅(shape을 맞춤) 후 진행
(공식 문서 참조)
~~~

>shape가 같은 경우 연산

In [3]:
x=np.arange(15).reshape(3,5)
y=np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.34467557 0.65418185 0.98485626 0.97427004 0.08368505]
 [0.32347944 0.21675468 0.51337614 0.03768437 0.58221228]
 [0.53302814 0.79736277 0.3512462  0.85735721 0.05905389]]


In [4]:
x+y

array([[ 0.34467557,  1.65418185,  2.98485626,  3.97427004,  4.08368505],
       [ 5.32347944,  6.21675468,  7.51337614,  8.03768437,  9.58221228],
       [10.53302814, 11.79736277, 12.3512462 , 13.85735721, 14.05905389]])

In [5]:
x*y

array([[ 0.        ,  0.65418185,  1.96971253,  2.92281011,  0.33474021],
       [ 1.61739719,  1.30052807,  3.59363298,  0.30147495,  5.23991048],
       [ 5.33028143,  8.77099046,  4.21495444, 11.14564371,  0.82675443]])

>Scalar(상수)와의 연산

In [7]:
x+2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [8]:
x**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]], dtype=int32)

In [9]:
x%2==0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

>shape이 다른 경우 연산

In [20]:
a=np.arange(12).reshape(4,3)
b=np.arange(100,103)
c=np.arange(1000,1004)
d=b.reshape(1,3)

print(a)
print(b)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]


In [21]:
a+b    #a+b는 계산이 잘 되지만 a+c는 shape가 다르므로 덧셈이 안된다. 

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [22]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(4, 3)
(3,)
(4,)
(1, 3)


In [23]:
a+d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])